apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-management-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-management
  template:
    metadata:
      labels:
        app: course-management
    spec:
      containers:
        - name: course-management
          image: course-management-service:latest
          ports:
            - containerPort: 3002
